baseURL = "https://ekme.se"
languageCode = "en-us"
title = "Morgan Ekmefjord"
theme = "archie"
copyright = "© Morgan Ekmefjord"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
mode = "auto"
useCDN = false
subtitle = ""
customcss = ["css/first.css"]
#[[params.social]]
#name = "GitHub"
#icon = "github"
#url = "https://github.com/athul/archie"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/athulcajay/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
